/**
 * Structured content for the Veldskoen Shoes USA growth case study.
 *
 * Claim guardrails: ~$250K/month revenue within 12 months and ~$30K/month
 * advertising budget are approved operating-history figures. Do not invent
 * ROAS, CPA, conversion lifts, customer counts, profit, or press claims.
 * Do not mix Slyde achievements into this story.
 */

export type MetaItem = { label: string; value: string };
export type MetricBlock = {
  value: string;
  label: string;
  supportingNote: string;
};
export type WorkflowStage = {
  id: string;
  title: string;
  description: string;
};
export type Lesson = { title: string; body: string };
export type LeadershipCard = { title: string; body: string };

export const veldskoenCaseStudy = {
  hero: {
    eyebrow: "Veldskoen Shoes USA",
    title: "Building a DTC Footwear Brand From $0 to $250K a Month",
    supportingHeadline:
      "Creating the positioning, product, Shopify experience, acquisition engine, and customer story behind a rapidly scaling U.S. footwear business.",
    intro:
      "Veldskoen began with an opportunity to introduce a distinctive South African footwear story to the U.S. market while building the commercial systems required to support a modern direct-to-consumer brand.\n\nAs Co-Founder and CEO of Veldskoen Shoes USA, I worked across brand strategy, product development, e-commerce, performance marketing, creative direction, packaging, customer experience, partnerships, and operations.\n\nWithin 12 months, the U.S. business grew from $0 to approximately $250,000 per month in revenue.",
    meta: [
      {
        label: "Role",
        value: "Co-Founder & CEO / Chief Storyteller",
      },
      { label: "Period", value: "August 2018 – December 2023" },
      {
        label: "Focus",
        value: "Brand Building, Product, E-Commerce & Growth",
      },
      { label: "Market", value: "United States" },
    ] satisfies MetaItem[],
    methodologyNote:
      "The $250,000 figure represents approximate monthly business revenue achieved within the first 12 months of the U.S. growth period, based on internal operating history and résumé records. Supporting historical platform evidence should be added when available. It is not profit and was not generated by advertising alone.",
    image: {
      src: "/images/work/veldskoen/hero.svg",
      alt: "Editorial visual suggesting footwear storytelling, Shopify commerce, and connected DTC growth for Veldskoen Shoes USA.",
    },
  },

  opportunity: {
    heading: "A Distinctive Product Needed a Distinctive U.S. Story",
    body: [
      "The opportunity was not simply to list another shoe online. The challenge was to introduce a product with a strong South African identity to a new market, communicate why it was different, and build enough trust for customers to purchase from an emerging U.S. brand.",
      "The commercial work needed to connect heritage, craftsmanship, color, comfort, product quality, modern design, and personality without turning the brand into a cultural cliché.",
    ],
    featuredQuestion:
      "How could we preserve what made the product distinctive while building a U.S. brand, customer experience, and growth engine capable of scaling?",
  },

  role: {
    heading: "Founder-Level Responsibility Across the Business",
    intro:
      "My role extended across the full customer and product journey rather than being limited to one marketing channel. I led, built, directed, managed, developed, coordinated, tested, improved, and scaled the work with specialists, partners, suppliers, and collaborators.",
    responsibilities: [
      "U.S. brand positioning",
      "Business and growth strategy",
      "Product storytelling",
      "Product development",
      "Shopify leadership",
      "Mobile-first merchandising",
      "Landing-page development",
      "Product-page optimization",
      "Conversion testing",
      "Paid acquisition",
      "Creative testing",
      "Email marketing",
      "Influencer and community marketing",
      "Packaging development",
      "Sustainable-practice development",
      "Product launches",
      "Supplier coordination",
      "Global production coordination",
      "Customer experience",
      "Team leadership",
      "Operational planning",
    ],
  },

  commercialResult: {
    heading: "From $0 to Approximately $250K Per Month Within 12 Months",
    metrics: [
      {
        value: "$0 → $250K",
        label: "Approximate Monthly Revenue",
        supportingNote:
          "Reached within the first 12 months of scaling Veldskoen Shoes USA.",
      },
      {
        value: "12 Months",
        label: "Time to Reach the Monthly Run Rate",
        supportingNote:
          "The result came from the combined brand, product, acquisition, e-commerce, and operating system.",
      },
      {
        value: "$30K/Month",
        label: "Advertising Budget Managed",
        supportingNote:
          "Across Facebook, Google, email, influencer, and social activity during the growth period.",
      },
    ] satisfies MetricBlock[],
    methodologyNote:
      "The revenue result reflects the combined contribution of product-market positioning, customer acquisition, Shopify execution, creative, product storytelling, merchandising, customer experience, and operational discipline. It should not be attributed to one campaign or channel.",
  },

  growthSystem: {
    heading: "Growth Came From a Connected Brand and Commerce System",
    image: {
      src: "/images/work/veldskoen/growth-system.svg",
      alt: "Conceptual loop connecting product story, brand positioning, Shopify, acquisition, creative testing, conversion, retention, and operations.",
    },
    stages: [
      {
        id: "origin",
        title: "Product and Origin Story",
        description:
          "Translate the product’s heritage, craftsmanship, design, color, and personality into a customer story that could be understood quickly.",
      },
      {
        id: "positioning",
        title: "U.S. Brand Positioning",
        description:
          "Build a differentiated market position suitable for the American footwear and lifestyle audience.",
      },
      {
        id: "shopify",
        title: "Shopify Experience",
        description:
          "Create a mobile-first path from discovery to product understanding and purchase.",
      },
      {
        id: "acquisition",
        title: "Customer Acquisition",
        description:
          "Use paid media, search, email, social, influencers, partnerships, and storytelling to introduce the brand.",
      },
      {
        id: "creative",
        title: "Creative Testing",
        description:
          "Test product imagery, stories, messages, formats, audiences, and landing experiences.",
      },
      {
        id: "conversion",
        title: "Conversion Optimization",
        description:
          "Improve merchandising, product pages, landing pages, navigation, trust, and purchase clarity.",
      },
      {
        id: "retention",
        title: "Retention and Community",
        description:
          "Deepen customer connection through brand storytelling, email, content, social interaction, and product experience.",
      },
      {
        id: "operations",
        title: "Operational Scale",
        description:
          "Coordinate marketing, creative, product, production, inventory, suppliers, packaging, distribution, and launch timing.",
      },
    ] satisfies WorkflowStage[],
    loopNote: "Operational scale reconnects to product and origin story as the business grows.",
  },

  brandPositioning: {
    heading: "Turning Product Origin Into Modern Brand Differentiation",
    body: [
      "The brand needed to feel authentic to its South African origin while remaining relevant to a modern U.S. customer.",
      "The positioning connected South African heritage, color and personality, quality craftsmanship, everyday comfort, modern styling, product authenticity, community, and responsible business practices.",
    ],
    principle:
      "The story had to make the product easier to understand—not distract customers from the product itself.",
  },

  productDevelopment: {
    heading: "Product Leadership Beyond Marketing",
    body: [
      "My background in product design allowed me to contribute across the complete product lifecycle rather than treating the product as something handed to marketing after development was finished.",
      "I coordinated assortment decisions, product stories, materials and construction communication, color and style presentation, packaging experience, supplier coordination, production timelines, global distribution considerations, launch planning, and customer feedback—without claiming sole design authorship for every product.",
    ],
    stages: [
      "Opportunity",
      "Concept and Design",
      "Product Positioning",
      "Production Coordination",
      "Packaging",
      "Digital Merchandising",
      "Launch",
      "Customer Feedback",
    ],
  },

  shopifyExperience: {
    heading: "Building the Digital Path From Discovery to Purchase",
    body: [
      "Shopify was the commercial center of the U.S. brand experience. The site needed to introduce an unfamiliar product, establish trust, answer customer questions, and make the purchase journey work well on mobile.",
    ],
    cards: [
      {
        title: "Mobile-First Merchandising",
        body: "Organize products and stories for customers arriving from social, advertising, search, and mobile devices.",
      },
      {
        title: "Product-Page Optimization",
        body: "Improve imagery, hierarchy, product explanation, sizing, benefits, trust, and calls to action.",
      },
      {
        title: "Landing-Page Testing",
        body: "Build campaign and product-entry experiences that matched the promise of the advertisement.",
      },
      {
        title: "Conversion Review",
        body: "Use customer behavior, testing, analytics, and commercial results to identify friction.",
      },
      {
        title: "Customer Education",
        body: "Explain the product clearly enough for customers to understand why it was different and whether it was right for them.",
      },
    ],
  },

  acquisition: {
    heading: "Building Demand Across Multiple Channels",
    body: [
      "The acquisition strategy combined product storytelling with disciplined performance marketing.",
      "I managed a marketing team and approximately $30,000 per month in advertising during the scaling period.",
    ],
    channels: [
      "Facebook and Instagram advertising",
      "Google advertising",
      "Email marketing",
      "Social content",
      "Influencer partnerships",
      "Community storytelling",
      "Product launches",
      "Landing pages",
    ],
    learningLoop: [
      "Customer Insight",
      "Creative Hypothesis",
      "Campaign",
      "Landing Experience",
      "Commercial Result",
      "Learning",
      "Next Test",
    ],
  },

  creativeTesting: {
    heading: "Creative Was Part of the Growth System",
    body: [
      "Creative development was not separated from performance. Product photography, founder storytelling, lifestyle context, color, customer questions, campaign messages, and landing experiences all contributed to how customers understood the brand.",
    ],
    areas: [
      "Product-first imagery",
      "Lifestyle photography",
      "Origin storytelling",
      "Customer-benefit messaging",
      "Color-led creative",
      "Founder narrative",
      "Social formats",
      "Campaign hooks",
      "Landing-page continuity",
      "Product education",
    ],
    principle:
      "The advertisement, landing page, product story, and customer experience needed to tell the same story.",
  },

  packaging: {
    heading: "The Brand Experience Continued After Checkout",
    body: [
      "Packaging was treated as part of the product and brand experience rather than a shipping afterthought.",
      "I coordinated premium packaging development across suppliers, design, production, timing, sustainability considerations, and the customer unboxing experience.",
    ],
    blocks: [
      {
        title: "Premium Customer Experience",
        body: "Packaging needed to protect the product, reinforce its positioning, and create a memorable first physical interaction with the brand.",
      },
      {
        title: "Responsible Development",
        body: "Sustainable and eco-conscious considerations were incorporated into packaging and supply-chain decision-making where practical—without claiming carbon neutrality or unverified certifications.",
      },
    ],
  },

  community: {
    heading: "Building More Than a Transaction",
    body: [
      "Veldskoen’s growth depended on creating an emotional reason to remember and share the product.",
      "The brand used product stories, social content, customer interaction, partnerships, personalities, and community participation to build recognition and trust.",
    ],
    areas: [
      "Founder storytelling",
      "Customer stories",
      "Social engagement",
      "Influencer relationships",
      "Product launches",
      "Community participation",
      "Partnership development",
    ],
  },

  leadership: {
    heading: "Scaling Required More Than Marketing",
    body: [
      "Reaching the growth result required coordinating creative, product, advertising, merchandising, suppliers, production, packaging, inventory, distribution, customer experience, and financial priorities.",
    ],
    cards: [
      {
        title: "Cross-Functional Direction",
        body: "Keep marketing, product, design, production, and operations aligned around the same priorities.",
      },
      {
        title: "Resource Allocation",
        body: "Direct budget, time, creative production, and attention toward the highest-impact needs.",
      },
      {
        title: "Launch Coordination",
        body: "Connect product readiness, inventory, site updates, advertising, content, email, and customer communication.",
      },
      {
        title: "Decision-Making",
        body: "Balance speed, brand standards, customer experience, cash, inventory, and sustainable growth.",
      },
      {
        title: "Team Leadership",
        body: "Set direction while relying on specialists, partners, suppliers, and collaborators to execute effectively.",
      },
    ] satisfies LeadershipCard[],
  },

  lessons: {
    heading: "The Lessons That Still Shape How I Build",
    items: [
      {
        title: "Brand and Performance Are Not Opposites",
        body: "Distinctive storytelling makes acquisition and conversion work stronger when it helps customers understand the product.",
      },
      {
        title: "Product Is Part of Marketing",
        body: "Growth becomes more sustainable when product development, packaging, merchandising, and customer feedback remain connected.",
      },
      {
        title: "Mobile Clarity Matters",
        body: "The complete customer story must work for someone arriving on a small screen with limited context.",
      },
      {
        title: "Growth Exposes Operational Weakness",
        body: "Marketing cannot scale responsibly when product, inventory, production, customer service, or fulfillment cannot support the demand.",
      },
      {
        title: "Customer Trust Compounds",
        body: "Every advertisement, product page, package, email, and customer interaction either strengthens or weakens the same relationship.",
      },
    ] satisfies Lesson[],
  },

  result: {
    heading: "The Result",
    body: [
      "Veldskoen Shoes USA grew from $0 to approximately $250,000 per month within 12 months.",
      "More importantly, the business demonstrated my ability to build a consumer brand across product, positioning, Shopify, acquisition, creative, conversion, packaging, customer experience, leadership, and operations.",
      "The experience continues to shape how I work today: start with a meaningful product, tell a clear story, connect every customer touchpoint, measure what happens, and build the operation required to support growth.",
    ],
    closing:
      "This was not a single-channel advertising result. It was the outcome of building the brand and commercial system together.",
  },

  relatedProjectIds: [
    "fishewear-growth-system",
    "slyde-handboards",
    "totely-ai-storage",
  ],

  relatedNotes: {
    "fishewear-growth-system":
      "Modernizing and growing an established DTC brand",
    "slyde-handboards":
      "Founder-led product development, investment, and brand building",
    "totely-ai-storage": "Building an AI-enabled product from zero",
  } as Record<string, string>,

  metadata: {
    title: "Veldskoen Growth Case Study | Steve Watts",
    description:
      "How Steve Watts helped build Veldskoen Shoes USA from $0 to approximately $250,000 per month by connecting product development, brand strategy, Shopify, performance marketing, creative, packaging, and DTC operations.",
  },
} as const;
